name: super_rich_text
description: The easiest way to style custom text snippets by creating your own bookmarks with links and functions.
version: 1.0.0
homepage: https://github.com/Bestfastfire/super_rich_text

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter